# Generated by Django 3.0.4 on 2020-03-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('table', 'date')},
        ),
    ]
